kind: pipeline
type: docker
name: default

environment:
  {}

steps:

- name: publish-image
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    dockerfile: standalone.dockerfile 
    context: .
    debug: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: opertusmundi/mapstore2
    tags:
    - "${DRONE_SEMVER_SHORT}"
    - "${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
    mirror: http://registry-mirror:5000

